//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmcData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderListView
    {
        public int OrderID { get; set; }
        public int StatusID { get; set; }
        public string Name { get; set; }
        public int Black { get; set; }
        public int Blue { get; set; }
        public int Red { get; set; }
        public int Green { get; set; }
        public int White { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> NumberOfProducts { get; set; }
    }
}
