//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnviromentLog
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int SourceID { get; set; }
        public double Reading { get; set; }
    
        public virtual Source Source { get; set; }
    }
}
