//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServer.ScadaWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ScadaWcf.IScada")]
    public interface IScada {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/AddResponse")]
        double Add(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Start", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/StartResponse")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Start", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Stop", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/StopResponse")]
        void Stop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Stop", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/StopResponse")]
        System.Threading.Tasks.Task StopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Resume", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/ResumeResponse")]
        void Resume();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/Resume", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/ResumeResponse")]
        System.Threading.Tasks.Task ResumeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/EmergencyStop", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/EmergencyStopResponse")]
        void EmergencyStop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IScada/EmergencyStop", ReplyAction="http://Microsoft.ServiceModel.Samples/IScada/EmergencyStopResponse")]
        System.Threading.Tasks.Task EmergencyStopAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScadaChannel : WebApiServer.ScadaWcf.IScada, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScadaClient : System.ServiceModel.ClientBase<WebApiServer.ScadaWcf.IScada>, WebApiServer.ScadaWcf.IScada {
        
        public ScadaClient() {
        }
        
        public ScadaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScadaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScadaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScadaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double n1, double n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double n1, double n2) {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        public void Stop() {
            base.Channel.Stop();
        }
        
        public System.Threading.Tasks.Task StopAsync() {
            return base.Channel.StopAsync();
        }
        
        public void Resume() {
            base.Channel.Resume();
        }
        
        public System.Threading.Tasks.Task ResumeAsync() {
            return base.Channel.ResumeAsync();
        }
        
        public void EmergencyStop() {
            base.Channel.EmergencyStop();
        }
        
        public System.Threading.Tasks.Task EmergencyStopAsync() {
            return base.Channel.EmergencyStopAsync();
        }
    }
}
